<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="5.0.18" />
    <ProjectReference Include="..\Admin.NET.Core\Admin.NET.Core.csproj" />
    <ProjectReference Include="..\Admin.NET.Core101\Admin.NET.Core101.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Seed/catalog-seeds.json" />
  </ItemGroup>
</Project>
