param(
    [Parameter(Mandatory = $true)]
    [string]$FrontendRoot
)

$ErrorActionPreference = 'Stop'
$sourcePath = Join-Path $FrontendRoot 'src/data/workflowSeed.ts'
$source = Get-Content -LiteralPath $sourcePath -Raw -Encoding UTF8
$pattern = '(?s)const workflowData = `\r?\n(?<data>.*?)\r?\n`\.trim\(\)'
$match = [regex]::Match($source, $pattern)
if (-not $match.Success) {
    throw "Cannot locate workflowData in $sourcePath"
}

$rows = $match.Groups['data'].Value -split '\r?\n'
if ($rows.Count -ne 334) {
    throw "Expected 334 workflow rows but found $($rows.Count)."
}

function Escape-CSharp([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

$ids = [System.Collections.Generic.List[string]]::new()
$items = [System.Collections.Generic.List[string]]::new()
for ($index = 0; $index -lt $rows.Count; $index++) {
    $number = $index + 1
    $key = 'workflow-model-{0:D4}' -f $number
    $guid = '10150000-0000-0000-0000-{0:D12}' -f $number
    $columns = $rows[$index].Split("`t")
    if ($columns.Count -lt 5) {
        throw "Workflow row $number has fewer than five columns."
    }

    $ids.Add("        [`"$key`"] = Guid.Parse(`"$guid`"),")
    $items.Add(@"
        new WorkflowNode101
        {
            Id = SeedIds101.Workflows["$key"],
            Department = "$(Escape-CSharp $columns[0])",
            Area = "$(Escape-CSharp $columns[1])",
            Process = "$(Escape-CSharp $columns[2])",
            Step = "$(Escape-CSharp $columns[3])",
            Post = "$(Escape-CSharp $columns[4])",
            OrderNo = $number,
            Enabled = true
        },
"@)
}

$seedDirectory = Join-Path $PSScriptRoot '../Admin.NET.Core101/Seed'
$idOutput = Join-Path $seedDirectory 'SeedIds101.Workflow.Generated.cs'
$itemOutput = Join-Path $seedDirectory 'WorkflowSeed101.Generated.cs'

$idContent = @"
// <auto-generated />
namespace Admin.NET.Core101.Seed;

public static partial class SeedIds101
{
    public static IReadOnlyDictionary<string, Guid> Workflows { get; } = new Dictionary<string, Guid>
    {
$($ids -join "`n")
    };
}
"@

$itemContent = @"
// <auto-generated />
using Admin.NET.Core101.Entity;

namespace Admin.NET.Core101.Seed;

public static class WorkflowSeed101
{
    public static IReadOnlyList<WorkflowNode101> Items { get; } = new[]
    {
$($items -join "")
    };
}
"@

Set-Content -LiteralPath $idOutput -Value $idContent -Encoding utf8NoBOM
Set-Content -LiteralPath $itemOutput -Value $itemContent -Encoding utf8NoBOM
Write-Output "Generated $($rows.Count) workflow rows."
